GET http://localhost:3000/ads

###

GET http://localhost:3000/categories/3/ads

###

POST http://localhost:3000/ads
Content-Type: application/json

{
    "title": "Bike to sell",
    "owner": "car.seller@gmail.com",
    "price": 10000,
    "location": "Paris",
    "categoryId": 1
}

###

DELETE http://localhost:3000/ads/25

###

PATCH http://localhost:3000/ads/5
Content-Type: application/json

{
    "title": "Bike to sell",
    "price": 300
}

###

PUT http://localhost:3000/ads/3
Content-Type: application/json

{
    "title": "Car to sell",
    "owner": "Johnny",
    "price": 3500,
    "location": "Paris",
    "categoryId" : 3
}