GET http://localhost:3000/ads

###

GET http://localhost:3000/categories/3/ads

###

POST http://localhost:3000/ads
Content-Type: application/json

{
    "title": "Fun Car",
    "description": "My Funny Car is for sale",
    "owner": "car.seller@gmail.com",
    "price": 300,
    "location": "Paris",
    "categoryId": 1
}

###

DELETE http://localhost:3000/ads/1

###

PUT http://localhost:3000/ads/2
Content-Type: application/json

{
    "title": "Kid's Bike",
    "description": "My Bike is for sale. Is in good shape !",
    "owner": "Johnny",
    "price": 150,
    "location": "Paris",
    "categoryId" : 3
}

###

PATCH http://localhost:3000/ads/3
Content-Type: application/json

{
    "title": "Bike to sell",
    "price": 300
}