GET http://localhost:5000/ads

###

GET http://localhost:5000/categories/3/ads

###

POST http://localhost:5000/ads
Content-Type: application/json

{
    "title": "Table",
    "description": "A simple table",
    "imgSrc":"/images/table.webp",
    "price": 120,
    "category": 1
}

###

POST http://localhost:5000/ads
Content-Type: application/json

{
    "title": "Dame-Jeanne",
    "description": "Super vase Dame-Jeanne au top !",
    "imgSrc":"/images/dame-jeanne.webp",
    "price": 75,
    "category": 1
}

###

DELETE http://localhost:5000/ads/3

###

PUT http://localhost:5000/ads/2
Content-Type: application/json

{
    "title": "Kid's Bike",
    "description": "My Bike is for sale. Is in good shape !",
    "owner": "Johnny",
    "price": 150,
    "location": "Paris",
    "categoryId" : 3
}

###

PATCH http://localhost:5000/ads/3
Content-Type: application/json

{
    "title": "Bike to sell",
    "price": 300
}